# Generated by Django 5.2 on 2025-06-02 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('deal_date', models.DateField()),
                ('submitted_date', models.DateField()),
                ('unit_no', models.CharField(max_length=20)),
                ('building_name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waiting_finance', 'Waiting for Finance'), ('pending_finance', 'Pending Finance'), ('entered_finance', 'Entered Finance')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deal_date'],
            },
        ),
    ]
