# Generated by Django 5.2 on 2025-06-03 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Deals_Management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_mobile', models.CharField(max_length=20)),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_nationality', models.CharField(max_length=100)),
                ('seller_source', models.CharField(max_length=255)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_mobile', models.CharField(max_length=20)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_nationality', models.CharField(max_length=100)),
                ('buyer_source', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
