# Generated by Django 5.2 on 2025-06-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Deals_Management', '0002_sourcedetails_alter_salesdeal_submitted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceDetails',
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='seller_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='seller_nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='seller_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
