# Generated by Django 5.2 on 2025-06-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Deals_Management', '0003_delete_sourcedetails_salesdeal_buyer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdeal',
            options={'ordering': ['-submitted_date']},
        ),
        migrations.RenameField(
            model_name='salesdeal',
            old_name='submitted_by',
            new_name='deal_submitted_by_agent',
        ),
        migrations.RemoveField(
            model_name='salesdeal',
            name='deal_date',
        ),
        migrations.RemoveField(
            model_name='salesdeal',
            name='status',
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_agency_brn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_agency_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_agent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_agent_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_agent_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='mediating_agency_brn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='mediating_agency_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='mediating_agent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='mediating_agent_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='mediating_agent_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='seller_agency_brn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='seller_agency_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='seller_agent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='seller_agent_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='seller_agent_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='buyer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='buyer_mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='buyer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='buyer_nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='buyer_source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='seller_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='seller_mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='seller_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='seller_nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='seller_source',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
