# Generated by Django 5.2 on 2025-06-04 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Deals_Management', '0004_alter_salesdeal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdeal',
            name='agent1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent1_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='agent1_commission',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='agent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent2_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='agent2_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='agent3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent3_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='agent3_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='aml',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='classic',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='comment_by_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='comment_by_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='force_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='kyc_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='less_outside_commission',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='net_commission',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='receipt_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waiting_finance', 'Waiting for Finance'), ('pending_finance', 'Pending Finance'), ('entered_finance', 'Entered Finance')], default='waiting_finance', max_length=30),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
