# Generated by Django 5.2 on 2025-06-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Deals_Management', '0005_salesdeal_agent1_salesdeal_agent1_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdeal',
            name='force_change',
        ),
    ]
