# Generated by Django 5.2 on 2025-06-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Deals_Management', '0006_remove_salesdeal_force_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_eid',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_poa_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_poa_eid',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyer_poa_passport_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyers_deposit_cheque_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='buyers_passport_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='form_f',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='kyc_or_approval_form',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='manager_cheque_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='new_title_deed',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='old_title_deed',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='owner_eid',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='owners_passport_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='screening',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='screening_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='seller_poa_passport_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='sellers_deposit_cheque_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='sellers_poa_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesdeal',
            name='sellers_poa_eid',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
