# Generated by Django 5.2 on 2025-06-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Deals_Management', '0007_salesdeal_buyer_eid_salesdeal_buyer_poa_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdeal',
            name='buyers_deposit_cheque_copy',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='buyers_passport_copy',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='form_f',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='manager_cheque_copy',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='new_title_deed',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='old_title_deed',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='owners_passport_copy',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='screening',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
