# Generated by Django 5.2 on 2025-06-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Deals_Management', '0008_alter_salesdeal_buyers_deposit_cheque_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdeal',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('waiting_finance', 'Waiting for Finance')], default='waiting_finance', max_length=30),
        ),
    ]
