# Generated by Django 5.2 on 2025-06-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Deals_Management', '0009_alter_salesdeal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdeal',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('waiting_finance', 'Waiting for Finance')], default='waiting_finance', max_length=30),
        ),
        migrations.AlterField(
            model_name='salesdeal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'submitted')], default='draft', max_length=30),
        ),
    ]
