# Generated by Django 5.2.1 on 2025-06-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentaldeals',
            options={},
        ),
    ]
