# Generated by Django 5.2.1 on 2025-06-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_rentaldeals_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentaldeals',
            options={'managed': False},
        ),
    ]
