# Generated by Django 5.2.1 on 2025-08-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dashboard_alter_rentalproperties_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managementreceipts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rentalproperties',
            options={'managed': False},
        ),
    ]
