# Generated by Django 5.2.1 on 2025-08-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_groupprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
