# Generated by Django 5.2.1 on 2025-08-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_groupprofile_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalproperties',
            options={},
        ),
    ]
