# Generated by Django 5.2.1 on 2025-08-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_rentalproperties_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalproperties',
            options={'managed': False},
        ),
    ]
