"""
Django settings for django_saas project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fh5_0e5k3g*1u_78@kglv40*5e@54-5d$9eauv8awg$52)n-*@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #apps
    'core',
    'Rental_Deal',
    "Sales_Deals_Management",
    "Third_Party_Receipts",
    "property_management_deals",
    "Rolemanagement",
    'django_multitenant',
   

    #rest_framework
    'rest_framework',  # Django REST Framework for API support'

    #filters
    'django_filters',
    # 'silk',  # Django Silk for profiling and monitoring
    'storages'
]

MIDDLEWARE = [ 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AccountMiddleware',
 ]

ROOT_URLCONF = 'django_saas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
          'DIRS': [
            BASE_DIR / 'templates',  # Project-level templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_saas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default':  {
    #     'ENGINE': 'django.db.backends.mysql',  # or 'sqlite3', 'mysql', etc.
    #     'NAME': os.getenv('DATABASE_NAME'),  # Default database name
    #     'USER': os.getenv('DATABASE_USER'),
    #     'PASSWORD': os.getenv('DATABASE_PASSWORD'),
    #     'HOST': os.getenv('DATABASE_HOST'),
    #     'PORT': os.getenv('DATABASE_PORT', '3306'),
    # }
       'default':  {
        'ENGINE': 'django.db.backends.mysql',  # or 'sqlite3', 'mysql', etc.
        'NAME':  "gopitest",  # Default database name
        'USER':  "root",
        'PASSWORD': "root",
        'HOST': "localhost",
        'PORT': "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# For development - global static folder
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # This is your project-level static folder
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

 
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
     
    
}


AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
print( f"AWS_ACCESS_KEY_ID: {AWS_ACCESS_KEY_ID}")  # Debugging line to check if the key is loaded
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_BUCKET')
AWS_S3_REGION_NAME = os.getenv('AWS_DEFAULT_REGION')  # default to Mumbai
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

# This is the key line: switch from local to S3 for media files

# Optional: where media files are stored within the bucket
MEDIA_LOCATION = os.getenv('MEDIA_LOCATION', 'media')
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{MEDIA_LOCATION}/'


DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

print("STORAGE USED:", DEFAULT_FILE_STORAGE)


LOGIN_REDIRECT_URL = '/'

# Redirects to this URL after logout
LOGOUT_REDIRECT_URL = '/login/'

# URL of the login view
LOGIN_URL = '/login/'

# URL of the logout view (optional, mostly used for redirection)
LOGOUT_URL = '/logout/'
# Custom user model
AUTH_USER_MODEL = 'core.Users'

# AWS S3 settings

AWS_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/rental/referencenumber_CP/'


ENV = "https://deal-saas.s3.ap-southeast-1.amazonaws.com/live"

