# Generated by Django 5.2.1 on 2025-06-05 13:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental_Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_date', models.DateField(default=datetime.date.today)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('deal_type', models.CharField(choices=[('new', 'New'), ('renewal', 'Renewal')], max_length=10)),
                ('project_name', models.CharField(max_length=200)),
                ('unit_number', models.CharField(max_length=50)),
                ('building_name', models.CharField(max_length=200)),
                ('deal_start_date', models.DateField()),
                ('deal_end_date', models.DateField()),
                ('property_usage', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], max_length=50, null=True)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('property_size', models.CharField(blank=True, max_length=50, null=True)),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mode_of_payment', models.CharField(blank=True, max_length=100, null=True)),
                ('premises_number', models.CharField(blank=True, max_length=50, null=True)),
                ('plot_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_mobile', models.CharField(max_length=20)),
                ('owner_nationality', models.CharField(max_length=50)),
                ('owner_email', models.EmailField(max_length=254)),
                ('tenant_name', models.CharField(max_length=100)),
                ('tenant_mobile', models.CharField(max_length=20)),
                ('tenant_nationality', models.CharField(max_length=50)),
                ('tenant_email', models.EmailField(max_length=254)),
                ('owner_agency_name', models.CharField(max_length=255)),
                ('owner_agency_brn', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_agent_name', models.CharField(max_length=255)),
                ('owner_agent_phone', models.CharField(max_length=20)),
                ('owner_agent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tenant_agency_name', models.CharField(max_length=255)),
                ('tenant_agency_brn', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant_agent_name', models.CharField(max_length=255)),
                ('tenant_agent_phone', models.CharField(max_length=20)),
                ('tenant_agent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mediating_agency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mediating_agency_brn', models.CharField(blank=True, max_length=100, null=True)),
                ('mediating_agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mediating_agent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mediating_agent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('less_outside_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classic', models.CharField(max_length=100)),
                ('agent1_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agent2_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agent3_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment_by_agent', models.TextField(blank=True, null=True)),
                ('comment_by_admin', models.TextField(blank=True, null=True)),
                ('receipt_no', models.CharField(max_length=100)),
                ('kyc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('aml', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('reject', 'Reject'), ('waiting', 'Waiting for Finance')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_entered_finance', models.BooleanField(default=False)),
                ('tenancy_contract', models.FileField(blank=True, null=True, upload_to='documents/tenancy_contracts/c4d356a5-b1da-44e8-9833-9a4db700ebea/')),
                ('title_deed', models.FileField(blank=True, null=True, upload_to='documents/title_deeds/39a412a3-5203-4d3b-9a59-b85a3e10eaf4/')),
                ('tenant_passport_visa_copy', models.FileField(blank=True, null=True, upload_to='documents/tenant_passports/4c0f4e2b-a55f-487f-9f71-6dc40a21cf96/')),
                ('owner_eid_copy', models.FileField(blank=True, null=True, upload_to='documents/owner_eid/107174c6-8f82-400f-b8f1-58b730ef540d/')),
                ('poa_pp', models.FileField(blank=True, null=True, upload_to='documents/poa_pp/d31c410a-8b53-4bd0-a997-963c5e5e3f4d/')),
                ('key_handover_form', models.FileField(blank=True, null=True, upload_to='documents/key_handover/882e2eef-0ed2-40d0-b31b-c5ac03cd87f9/')),
                ('tenancy_application_form', models.FileField(blank=True, null=True, upload_to='documents/tenancy_applications/aee63204-e7be-42a0-aed8-7dcae93a6748/')),
                ('owner_passport_copy', models.FileField(blank=True, null=True, upload_to='documents/owner_passports/68880d8e-2590-464c-b4c6-4293681750d7/')),
                ('ejari', models.FileField(blank=True, null=True, upload_to='documents/ejari/44de271d-46b5-4b93-b339-a0fec0662d2a/')),
                ('tenants_eid_copy', models.FileField(blank=True, null=True, upload_to='documents/tenant_eid/896643b3-b2ce-4c8f-a7ec-c463a8e837fd/')),
                ('rental_deposit_rental_cheque_copy', models.FileField(blank=True, null=True, upload_to='documents/cheques/68700afa-d773-4828-a92b-ccf51bd69236/')),
                ('poa_copy', models.FileField(blank=True, null=True, upload_to='documents/poa_copy/62b22384-b98b-4813-b1d8-80576cc216b3/')),
                ('kyc_form', models.FileField(blank=True, null=True, upload_to='documents/kyc_forms/cfe253f9-d476-4bb0-83d8-aa3dfaf1e5f5/')),
                ('screening', models.FileField(blank=True, null=True, upload_to='documents/screenings/8cf836f7-e1ab-4022-880a-191f23a721b8/')),
                ('screening_comments', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('agent1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent1_commissions', to=settings.AUTH_USER_MODEL)),
                ('agent2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent2_commissions', to=settings.AUTH_USER_MODEL)),
                ('agent3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent3_commissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
