# Generated by Django 5.2.1 on 2025-06-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_Deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_deal',
            name='ejari',
            field=models.FileField(blank=True, null=True, upload_to='documents/ejari/613da283-e24b-40d0-8513-83baf94069dc/'),
        ),
        migrations.AlterField(
            model_name='rental_deal',
            name='key_handover_form',
            field=models.FileField(blank=True, null=True, upload_to='documents/key_handover/f57e20bd-06dd-4595-9964-55a839ac3731/'),
        ),
        migrations.AlterField(
            model_name='rental_deal',
            name='kyc_form',
            field=models.FileField(blank=True, null=True, upload_to='documents/kyc_forms/8d412c1b-9dc3-41aa-b0b1-8127714afd8f/'),
        ),
        migrations.AlterField(
            model_name='rental_deal',
            name='owner_eid_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/owner_eid/29c95adf-183f-476e-aa44-ad3e6fef7397/'),
        ),
        migrations.AlterField(
            model_name='rental_deal',
            name='owner_passport_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/owner_passports/0a05957c-9620-4752-aef6-e35968f94aab/'),
        ),
        migrations.AlterField(
            model_name='rental_deal',
            name='poa_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/poa_copy/0d2f16e3-f8ba-4ad3-b7f5-d8b92a34ea6f/'),
        ),
        migrations.AlterField(
            model_name='rental_deal',
            name='poa_pp',
            field=models.FileField(blank=True, null=True, upload_to='documents/poa_pp/e7bc5cee-c312-47a5-bca0-4a727e1d70c2/'),
        ),
        migrations.AlterField(
            model_name='rental_deal',
            name='rental_deposit_rental_cheque_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/cheques/35ce713d-f07e-4953-b64b-dd4fb7969cf6/'),
        ),
        migrations.AlterField(
            model_name='rental_deal',
            name='screening',
            field=models.FileField(blank=True, null=True, upload_to='documents/screenings/392f2b1e-11ed-4915-ab9c-c227edd8b4d5/'),
        ),
        migrations.AlterField(
            model_name='rental_deal',
            name='tenancy_application_form',
            field=models.FileField(blank=True, null=True, upload_to='documents/tenancy_applications/1fc1b5d3-1438-48b3-9b01-41e23e642907/'),
        ),
        migrations.AlterField(
            model_name='rental_deal',
            name='tenancy_contract',
            field=models.FileField(blank=True, null=True, upload_to='documents/tenancy_contracts/a5d083c4-422e-4d4c-8dec-84880dd4326f/'),
        ),
        migrations.AlterField(
            model_name='rental_deal',
            name='tenant_passport_visa_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/tenant_passports/d1b2733f-50bd-4aaa-b5a8-09375d72ea71/'),
        ),
        migrations.AlterField(
            model_name='rental_deal',
            name='tenants_eid_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/tenant_eid/c4b15265-0095-425c-8878-ea65aac497bd/'),
        ),
        migrations.AlterField(
            model_name='rental_deal',
            name='title_deed',
            field=models.FileField(blank=True, null=True, upload_to='documents/title_deeds/649c1b48-aa03-4cce-8ec2-5fe11989e76e/'),
        ),
    ]
